x=c(1,2,3)
y=1:
x
y
z=c("a","b","c")
z
k=c("Matemáticas"=8.2,"Fisica"=6.5,"Economía"=4.5)
names(k)
length(k)
c(1,"a","k")
j=c(4,7,9,10,12)
j[c(F,F,T,F,F)]
x[2]
x[2]=14
x=c(1,2,3)
c(x,c(4,5))
x=c("a","b","c","d","e")
x[-3]
sexo=factor(c("mujer","hombre","mujer"))
sexo
class(sexo)
str(sexo)

list("nombre"="María","edad"=21,"dirección"=list("calle"="Delicias","numero"=24,"municipio"="Madrid"))
